{"pr_number": 61359, "pr_title": "Suppress noisy SSL exceptions", "pr_author": "DaveCTurner", "pr_createdAt": "2020-08-20T08:26:09Z", "pr_url": "https://github.com/elastic/elasticsearch/pull/61359", "timeline": [{"oid": "37db818a436770f2a5410d145af13e1c4363af4b", "url": "https://github.com/elastic/elasticsearch/commit/37db818a436770f2a5410d145af13e1c4363af4b", "message": "Suppress noisy SSL exceptions\n\nIf a TLS-protected connection closes unexpectedly then today we often\nemit a `WARN` log, typically one of the following:\n\n    io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)\n\n    io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake\n\nWe typically only report unexpectedly-closed connections at `DEBUG`\nlevel, but these two messages don't follow that rule and generate a lot\nof noise as a result. This commit adjusts the logging to report these\ntwo exceptions at `DEBUG` level only.", "committedDate": "2020-08-20T08:20:50Z", "type": "commit"}, {"id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3Mzc2MDkyMQ==", "url": "https://github.com/elastic/elasticsearch/pull/61359#discussion_r473760921", "body": "We were already checking for `Received close_notify during handshake`, just not within a `DecoderException`. Not sure whether this was a mistake or whether we do sometimes see this exception unwrapped too.\r\n\r\nAlso not sure what the implications for the `nio` transport since the `DecoderException` wrapper is Netty-specific.", "bodyText": "We were already checking for Received close_notify during handshake, just not within a DecoderException. Not sure whether this was a mistake or whether we do sometimes see this exception unwrapped too.\nAlso not sure what the implications for the nio transport since the DecoderException wrapper is Netty-specific.", "bodyHTML": "<p dir=\"auto\">We were already checking for <code>Received close_notify during handshake</code>, just not within a <code>DecoderException</code>. Not sure whether this was a mistake or whether we do sometimes see this exception unwrapped too.</p>\n<p dir=\"auto\">Also not sure what the implications for the <code>nio</code> transport since the <code>DecoderException</code> wrapper is Netty-specific.</p>", "author": "DaveCTurner", "createdAt": "2020-08-20T08:30:34Z", "path": "x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/transport/SSLExceptionHelper.java", "diffHunk": "@@ -22,6 +24,11 @@ public static boolean isNotSslRecordException(Throwable e) {\n     }\n \n     public static boolean isCloseDuringHandshakeException(Throwable e) {\n+        return isCloseDuringHandshakeSSLException(e)\n+                || isCloseDuringHandshakeSSLException(e.getCause());", "originalCommit": "37db818a436770f2a5410d145af13e1c4363af4b", "replyToReviewId": null, "replies": null, "type": "inlineReview"}]}